In [1]:
!pip install numpy

In [7]:
import numpy as np
##create array using numpy
##1D array
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [ ]:
arr2 =np.array([1,2,3,4,5])
arr2.reshape(1,5)##1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [ ]:
##2D array
arr2=np.array([[1,2,3,4,5],[1,2,3,5,6]])
print(arr2.shape) ##(2,5) 2 row and 5 column
print(arr2) 

(2, 5)
[[1 2 3 4 5]
 [1 2 3 5 6]]


In [ ]:
## array with inbuilt function
np.arange(0,10,2) ##(0,10) use number from 1 to 10 and 2 after choose every element skip the element after the choosen element.

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))## 3 row and 4 column with number 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(3) ##identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
## attributes of numpy array

arr = np.array([[1,2,3],[4,5,6]])

print("Array: \n",arr)
print("shape: \n",arr.shape)
print("number of dimension: \n",arr.ndim)
print("size(num of elements): \n",arr.size)
print("data type: \n",arr.dtype)
print("item size(in bytes): \n",arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
shape: 
 (2, 3)
number of dimension: 
 2
size(num of elements): 
 6
data type: 
 int64
item size(in bytes): 
 8


In [22]:
##numpy veactorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
##element wise addition
print("addition:",arr1+arr2)
##substraction
print("substraction:", arr1-arr2)
##multiplication
print("multiplication:", arr1*arr2)
print("division:", arr1/arr2)

addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [23]:
##universal function
arr=np.array([2,3,4,5,6])
##squart root
print(np.sqrt(arr))
##exponantial
print(np.exp(arr))
##sine
print(np.sin(arr))
##natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [32]:
##array slicing and indexing operation
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n", arr)

print(arr[0][0])
print(arr[1:,2:]) ##pick up 7,8,11,12 from matrix
print(arr[0:2]) ##o/p: 1,2,3,4,5,6,7,8
print(arr[0:2,2:])



Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[ 7  8]
 [11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[3 4]
 [7 8]]


In [39]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [42]:
arr[1:,0:2]

array([[ 5,  6],
       [ 9, 10]])

In [43]:
##MOdify the element
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [46]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [47]:
##statistical concept--normalization
##to have mean if 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

##calculate mean sand standard deviaton
mean =np.mean(data)
std_dev = np.std(data)
##normaliza the data
normalized_data = (data-mean)/std_dev
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
##mean, median, mode, standard deviation
data= np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data)
print("mean",mean)

median = np.median(data)
print("median",median)

std_dev = np.std(data)
print("standard deviation",std_dev)

variance = np.var(data)
print("variance:", variance)

mean 5.5
median 5.5
standard deviation 2.8722813232690143
variance: 8.25


In [56]:
##logical operation

data= np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])